@local_dev_env
Feature: RabbitMQ management UI is reachable with documented credentials
  As a Northwoods Traverse developer
  I want the RabbitMQ management interface to be accessible with the documented default credentials
  So that I can inspect queues, exchanges, and bindings without additional configuration

  # Traces to: design_local_dev_env.md — AC-3

  # --- Automatable Acceptance Criteria ---

  @AC-3
  Scenario: RabbitMQ management UI is accessible at localhost:15672 with default credentials
    Given the "traverse-rabbitmq" container is healthy
    When the developer opens "http://localhost:15672" in a browser
    And they enter the username "traverse" and password "traverse_dev" from the ".env" file
    Then the RabbitMQ management dashboard loads successfully
    And the default virtual host "/" is visible in the vhost list
    And no additional vhosts or queues are pre-configured

  @AC-3
  Scenario: RabbitMQ AMQP port is reachable on the documented port
    Given the "traverse-rabbitmq" container is healthy
    When a client attempts a TCP connection to "localhost" on port 5672
    Then the connection is accepted by the RabbitMQ AMQP listener

  @AC-3
  Scenario: RabbitMQ management credentials can be overridden via the .env file
    Given a developer has set "RABBITMQ_USER=myuser" and "RABBITMQ_PASSWORD=mypassword" in their local ".env" file
    And the "traverse-rabbitmq" container has started with those environment values loaded
    When the developer opens "http://localhost:15672"
    And they log in with username "myuser" and password "mypassword"
    Then the RabbitMQ management dashboard loads successfully
    And the default credentials "traverse" / "traverse_dev" are no longer accepted

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 15:00
