@local_dev_env
Feature: API service stubs respond to health checks on their assigned ports
  As a Northwoods Traverse developer
  I want each backend service stub to be reachable on its designated port and report a healthy status
  So that the Angular frontend proxy and any cross-service calls have a live target to communicate with

  # Traces to: design_local_dev_env.md — AC-5

  # --- Automatable Acceptance Criteria ---

  @AC-5
  Scenario Outline: Each API stub responds healthy on its assigned port
    Given the "<service_name>" container is healthy
    And PostgreSQL and RabbitMQ are both healthy
    When a request is made to "http://localhost:<port>/health/live"
    Then the response status is 200 OK
    And the response body is {"status":"Healthy"}

    Examples:
      | service_name        | port |
      | traverse-workflow   | 5001 |
      | traverse-kpi        | 5002 |
      | traverse-admin      | 5003 |
      | traverse-notifications | 5004 |
      | traverse-reporting  | 5005 |
      | traverse-aicopilot  | 5006 |
      | traverse-compliance | 5007 |
      | traverse-search     | 5008 |
      | traverse-calendar   | 5009 |

  @AC-5
  Scenario: API stubs do not start before PostgreSQL and RabbitMQ are ready
    Given Docker Compose has been invoked with "docker compose up"
    When PostgreSQL has not yet reached its healthy state
    Then none of the nine API stub containers begin their startup sequence
    And the Compose log stream shows the stubs waiting on the "service_healthy" condition

  @AC-5
  Scenario: Angular proxy reaches a backend service health endpoint via the proxy configuration
    Given all nine API stub containers are healthy
    And the Angular development server is running with "ng serve --proxy-config proxy.conf.json"
    When the developer's browser or a test client requests "/api/workflow/health/live" from "http://localhost:4200"
    Then the proxy forwards the request to "http://localhost:5001/health/live"
    And the response body is {"status":"Healthy"}
    And no CORS error or proxy timeout is observed

  @AC-5
  Scenario Outline: Each API stub port can be overridden via the .env file
    Given a developer has set "<env_var>=<override_port>" in their local ".env" file
    And the "<service_name>" container has started with that environment value loaded
    When a request is made to "http://localhost:<override_port>/health/live"
    Then the response status is 200 OK
    And "http://localhost:<default_port>/health/live" is no longer bound on the host

    Examples:
      | service_name        | env_var           | default_port | override_port |
      | traverse-workflow   | WORKFLOW_PORT     | 5001         | 6001          |
      | traverse-kpi        | KPI_PORT          | 5002         | 6002          |
      | traverse-admin      | ADMIN_PORT        | 5003         | 6003          |

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 15:00
