@local_dev_env
Feature: Full development stack starts with a single command
  As a Northwoods Traverse developer
  I want the entire local development environment to come online with one command
  So that I can run, debug, and integration-test the platform without manually
  installing or configuring any infrastructure component

  # Traces to: design_local_dev_env.md — AC-1

  # --- Automatable Acceptance Criteria ---

  @AC-1
  Scenario: docker compose up brings all containers to a healthy state within 90 seconds
    Given a developer has cloned the Northwoods Traverse repository
    And Docker Desktop is running on their machine
    And no volumes from a previous run exist
    When the developer runs "docker compose up" from the repository root
    Then the "traverse-postgres" container reaches the healthy state
    And the "traverse-rabbitmq" container reaches the healthy state
    And the "traverse-n8n" container reaches the healthy state
    And all nine API stub containers reach the healthy state
    And the total time from command execution to all containers healthy does not exceed 90 seconds
    And no container enters a restart loop or exits with an error

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 15:00
