@local_dev_env
Feature: README quickstart enables a new developer to run the full stack without prior knowledge
  As a new Northwoods Traverse developer
  I want the README quickstart section to be accurate and copy-pasteable
  So that I can reach a working local environment by following documented steps verbatim

  # Traces to: design_local_dev_env.md — AC-6

  # --- Automatable Acceptance Criteria ---

  @AC-6
  Scenario: A developer following the README quickstart can start the full stack
    Given a developer has cloned the Northwoods Traverse repository to a clean machine
    And Docker Desktop is running
    When the developer runs "cp .env.example .env" as documented in the quickstart
    And the developer runs "docker compose up" as documented in the quickstart
    Then all containers reach the healthy state without any command not listed in the quickstart
    And the developer did not need to install PostgreSQL, RabbitMQ, or n8n manually

  @AC-6
  Scenario: A developer following the README quickstart can verify the stack is working
    Given the full stack is running following the quickstart steps
    When the developer runs "curl http://localhost:5001/health/live" as documented in the README verification block
    Then the response body is {"status":"Healthy"}
    When the developer opens "http://localhost:15672" as documented
    Then the RabbitMQ management UI loads
    When the developer opens "http://localhost:5678" as documented
    Then the n8n editor loads without a login prompt

  @AC-6
  Scenario: The Angular shell is reachable after following the ng serve instructions in the README
    Given the full stack is running following the quickstart steps
    When the developer runs the "npm install" and "ng serve --proxy-config proxy.conf.json" commands documented in the README
    And the developer opens "http://localhost:4200"
    Then the Angular shell application loads in the browser
    And a proxied request to "/api/workflow/health/live" from the browser resolves successfully to the Workflow API

  @AC-6
  Scenario: The README documents how to stop and clean up the environment
    Given the developer is reading the README for the first time
    When they locate the "Stop and clean up" section
    Then the section contains a command to stop containers while keeping data volumes
    And the section contains a separate command to stop containers and delete all data volumes
    And the distinction between the two commands is clearly explained

  @AC-6
  Scenario: The README documents how to override default ports and credentials
    Given the developer is reading the README for the first time
    When they locate the port map or troubleshooting section
    Then the section lists every default host port for every service
    And the section explains that ports and credentials can be overridden by editing the local ".env" file
    And an example of setting "POSTGRES_PORT=5433" to resolve a port conflict is present

  # --- Human-Validation-Only Criteria ---
  # The following aspect of AC-6 requires human judgment and cannot be fully
  # expressed as an automated Gherkin scenario. It is documented here for
  # traceability and will be handled during validate-acceptance Phase 4.

  # @AC-6 @human-validation: README prose is clear, concise, and understandable by a developer
  # unfamiliar with the project.
  # Reason: "Accurate and copy-pasteable" has an automatable dimension (commands work verbatim)
  # which is covered by the scenarios above, but the clarity and readability of the prose is
  # a subjective quality that requires human review.
  # Reviewer: Dev Lead

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 15:00
