@local_dev_env
Feature: n8n workflow editor is reachable without authentication and with a mounted workflows directory
  As a Northwoods Traverse developer
  I want the n8n editor to load immediately without a login prompt
  So that I can build and inspect automation workflows during local development

  # Traces to: design_local_dev_env.md — AC-4

  # --- Automatable Acceptance Criteria ---

  @AC-4
  Scenario: n8n editor loads at localhost:5678 without requiring credentials
    Given the "traverse-n8n" container is healthy
    When the developer opens "http://localhost:5678" in a browser
    Then the n8n editor interface loads without displaying a login or credential prompt
    And the editor is immediately usable for creating and inspecting workflows

  @AC-4
  Scenario: Workflow files saved in n8n are reflected in the host-side workflows directory
    Given the "traverse-n8n" container is healthy
    And the host directory "n8n/workflows/" exists at the repository root
    When a developer saves a workflow inside the n8n editor
    Then a corresponding workflow JSON file is created or updated in "n8n/workflows/" on the host machine
    And the file is visible to the developer's source control tooling so it can be committed

  @AC-4
  Scenario: The n8n port can be overridden via the .env file
    Given a developer has set "N8N_PORT=5699" in their local ".env" file
    And the "traverse-n8n" container has started with that environment value loaded
    When the developer opens "http://localhost:5699"
    Then the n8n editor loads successfully
    And "http://localhost:5678" is no longer bound on the host

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 15:00
