@local_dev_env
Feature: PostgreSQL databases are provisioned automatically on first start
  As a Northwoods Traverse developer
  I want each service to have its own isolated database created automatically
  So that no manual database setup is required and each service owns its own data boundary

  # Traces to: design_local_dev_env.md — AC-2

  # --- Automatable Acceptance Criteria ---

  @AC-2
  Scenario: init.sql creates all nine service databases on a fresh volume
    Given no "postgres-data" volume exists from a previous run
    When the developer runs "docker compose up" from the repository root
    And the "traverse-postgres" container reaches the healthy state
    Then exactly nine databases are present in the PostgreSQL instance
    And the databases are owned by the configured administrator user
    And no unexpected databases beyond the nine service databases and the default "postgres" database exist

  @AC-2
  Scenario Outline: Each service database is individually reachable
    Given the "traverse-postgres" container is healthy following a first-start initialisation
    When a client connects to the PostgreSQL instance and queries the list of databases
    Then a database named "<database_name>" exists
    And the configured administrator user has full access to "<database_name>"

    Examples:
      | database_name          |
      | traverse_workflow      |
      | traverse_kpi           |
      | traverse_admin         |
      | traverse_notifications |
      | traverse_reporting     |
      | traverse_aicopilot     |
      | traverse_compliance    |
      | traverse_search        |
      | traverse_calendar      |

  @AC-2
  Scenario: init.sql does not re-run when the data volume already exists
    Given a "postgres-data" volume already contains initialised PostgreSQL data
    When the developer runs "docker compose up" again
    And the "traverse-postgres" container reaches the healthy state
    Then the nine service databases from the previous run are still present
    And no data loss occurs as a result of the restart

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 15:00
