@api_stubs
Feature: All nine API stub projects compile successfully as part of the solution
  As a platform developer
  I want all nine service API projects registered in the solution and compiling cleanly
  So that every Phase 1 story has a correctly-wired, warning-free project to extend

  # Traces to: design_api_stubs.md

  # --- Automatable Acceptance Criteria ---

  @AC-1
  Scenario: All nine API stub projects build with zero errors and zero warnings
    Given the repository root contains a Traverse.sln solution file
    And the solution includes a "services" solution folder
    And all nine service API projects are registered under the "services" folder:
      | project                            |
      | Traverse.Workflow.Api              |
      | Traverse.KPI.Api                   |
      | Traverse.Admin.Api                 |
      | Traverse.Notifications.Api         |
      | Traverse.Reporting.Api             |
      | Traverse.AICopilot.Api             |
      | Traverse.Compliance.Api            |
      | Traverse.Search.Api                |
      | Traverse.Calendar.Api              |
    And the .NET SDK 10.0.103 is active (as pinned by global.json in the repository root)
    When "dotnet build Traverse.sln --no-incremental" is executed from the repository root
    Then the build output reports "Build succeeded"
    And the build output reports "0 Error(s)"
    And the build output reports "0 Warning(s)"
    And all seventeen projects appear in the solution list (8 shared + 9 API stubs)

# Generated by skill: generate-gherkin v2.2.0 | 2026-05-04 10:00
