@api_stubs
Feature: All nine API service containers start and report healthy via docker compose
  As a platform operator
  I want all nine services to start together using docker compose and pass their health checks
  So that the local development environment is fully operational for Phase 1 story development

  # Traces to: design_api_stubs.md

  # --- Automatable Acceptance Criteria ---

  @AC-4
  Scenario: All nine API containers start healthy when launched with the api compose profile
    Given the docker-compose.yml file defines nine API service entries under the "api" profile:
      | service           |
      | workflow-api      |
      | kpi-api           |
      | admin-api         |
      | notifications-api |
      | reporting-api     |
      | aicopilot-api     |
      | compliance-api    |
      | search-api        |
      | calendar-api      |
    And each service entry references a Dockerfile that exists at its expected path
    And the supporting infrastructure containers (postgres, rabbitmq) are running
    When "docker compose --profile api up --build -d" is executed from the repository root
    And the system waits for all containers to complete their health checks
    Then all nine API service containers show a status of "healthy" in "docker compose ps"
    And no API service container is in a "starting", "unhealthy", or "exited" state

# Generated by skill: generate-gherkin v2.2.0 | 2026-05-04 10:00
