@api_stubs
Feature: Each API stub service exposes a live health check endpoint on its designated port
  As a platform operator
  I want each service to respond to liveness health checks on its expected port
  So that container orchestration and monitoring tools can confirm each service is alive

  # Traces to: design_api_stubs.md

  # --- Automatable Acceptance Criteria ---

  @AC-2
  Scenario Outline: Health check endpoint returns Healthy status for each service
    Given all nine API containers have been started with "docker compose --profile api up"
    And the "<service>" container is running and bound to host port <port>
    When a GET request is made to "http://localhost:<port>/health/live"
    Then the response status is 200 OK
    And the response body contains "status": "Healthy"

    Examples:
      | service           | port |
      | workflow-api      | 5001 |
      | kpi-api           | 5002 |
      | admin-api         | 5003 |
      | notifications-api | 5004 |
      | reporting-api     | 5005 |
      | aicopilot-api     | 5006 |
      | compliance-api    | 5007 |
      | search-api        | 5008 |
      | calendar-api      | 5009 |

  @AC-2
  Scenario Outline: Readiness health check endpoint returns Healthy status for each service
    Given all nine API containers have been started with "docker compose --profile api up"
    And the "<service>" container is running and bound to host port <port>
    When a GET request is made to "http://localhost:<port>/health/ready"
    Then the response status is 200 OK
    And the response body contains "status": "Healthy"

    Examples:
      | service           | port |
      | workflow-api      | 5001 |
      | kpi-api           | 5002 |
      | admin-api         | 5003 |
      | notifications-api | 5004 |
      | reporting-api     | 5005 |
      | aicopilot-api     | 5006 |
      | compliance-api    | 5007 |
      | search-api        | 5008 |
      | calendar-api      | 5009 |

# Generated by skill: generate-gherkin v2.2.0 | 2026-05-04 10:00
