@api_stubs
Feature: Each API stub service has a Dockerfile that builds successfully using the four-stage pattern
  As a platform developer
  I want each service to have a correctly structured multi-stage Dockerfile
  So that Docker images can be built reliably in CI and locally without SDK tools in the final image

  # Traces to: design_api_stubs.md

  # --- Automatable Acceptance Criteria ---

  @AC-3
  Scenario Outline: Service Dockerfile exists and builds to the runtime stage without errors
    Given the repository root contains the file "docker/<service_folder>/Dockerfile"
    And the Dockerfile defines exactly four stages: restore, build, publish, and runtime
    And the build context is the repository root
    When "docker build -f docker/<service_folder>/Dockerfile . --target runtime --no-cache" is executed
    Then the image builds successfully with exit code 0
    And no build errors are reported

    Examples:
      | service_folder | project_name               |
      | workflow       | Traverse.Workflow.Api      |
      | kpi            | Traverse.KPI.Api           |
      | admin          | Traverse.Admin.Api         |
      | notifications  | Traverse.Notifications.Api |
      | reporting      | Traverse.Reporting.Api     |
      | aicopilot      | Traverse.AICopilot.Api     |
      | compliance     | Traverse.Compliance.Api    |
      | search         | Traverse.Search.Api        |
      | calendar       | Traverse.Calendar.Api      |

# Generated by skill: generate-gherkin v2.2.0 | 2026-05-04 10:00
