@angular_shell
Feature: Auth service stub and route guards protect authenticated routes
  As a developer implementing Phase 1 screens
  I want authGuard and adminGuard to protect feature routes from the start
  So that the routing security contract is in place before real IdP integration

  # Traces to: design_angular_shell.md §2 US-004 and US-005

  # --- Automatable Acceptance Criteria ---

  @AC-016
  Scenario: Auth service stub provides the required contract methods in dev mode
    Given the Angular application has started in development mode
    When the AuthService is injected and its methods are called
    Then isAuthenticated() returns true (dev default)
    And hasRole('admin') returns true (dev default persona includes admin)
    And getToken() returns null (no real IdP token in Phase 0)

  @AC-017
  Scenario: Unauthenticated user is redirected to login with return URL
    Given a user is not authenticated (isAuthenticated returns false)
    When the user attempts to navigate to a protected route "/dashboard"
    Then the router redirects the user to "/login"
    And the redirect URL includes a returnUrl query parameter with the value "/dashboard"

  @AC-018
  Scenario: Authenticated non-admin user is redirected to the unauthorized page
    Given a user is authenticated
    And the user does not have the 'admin' role
    When the user attempts to navigate to an admin-protected route
    Then the router redirects the user to "/unauthorized"
    And the unauthorized page is displayed

  @AC-021
  Scenario Outline: AppRoutes constant provides typed path entries for all module routes
    Given the AppRoutes constant is imported from the core routes module
    When the route key "<route_key>" is accessed on AppRoutes
    Then the resolved path is "<expected_path>"

    Examples:
      | route_key          | expected_path       |
      | login              | /login              |
      | unauthorized       | /unauthorized       |
      | dashboard          | /dashboard          |
      | workflow           | /workflow           |
      | kpi                | /kpi                |
      | admin              | /admin              |
      | cases              | /cases              |
      | workItems          | /work-items         |
      | notifications      | /notifications      |
      | reporting          | /reporting          |
      | aiCopilot          | /ai-copilot         |
      | compliance         | /compliance         |
      | supervisorActions  | /supervisor         |
      | search             | /search             |
      | calendar           | /calendar           |
      | deputyDashboard    | /deputy             |

  @AC-022
  Scenario: Dynamic path helper generates correct parameterised route paths
    Given the AppRoutes constant is imported from the core routes module
    When the caseDetail helper is called with the case identifier "abc-123"
    Then the returned path is "/cases/abc-123"
    And when the workItemDetail helper is called with identifier "wi-456"
    Then the returned path is "/work-items/wi-456"

  # --- Human-Validation-Only Criteria ---
  # The following acceptance criteria require inspection of source file contents
  # and cannot be expressed as automated runtime Gherkin scenarios.
  # They are documented here for traceability and will be handled by validate-acceptance Phase 4.

  # @AC-019 [Human validation]: authGuard and adminGuard are implemented as functional
  #   CanActivateFn — not class-based guards.
  # Reason: The functional vs class-based distinction is an implementation detail visible only
  #   in the source code. From the outside, both forms produce identical routing behaviour;
  #   the observable outcomes are fully covered by AC-017 and AC-018.
  # Reviewer: Dev Lead (code review)

  # @AC-020 [Human validation]: AppRoutes is exported as a const object from
  #   app/core/routes/app-routes.ts (file path and export form verification).
  # Reason: Verifies TypeScript module structure and file location, not a runtime behaviour.
  #   The runtime correctness of the routes is covered by AC-021 and AC-022.
  # Reviewer: Dev Lead

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 10:00
