@angular_shell
Feature: Environment files and proxy configuration wire backend service URLs
  As a developer
  I want environment files with correct service URL maps and a proxy config for all nine backends
  So that HTTP calls to /api/{service} resolve correctly in local dev without CORS issues

  # Traces to: design_angular_shell.md §2 US-008

  # --- Automatable Acceptance Criteria ---

  @AC-036
  Scenario Outline: Angular dev server proxies API requests to the correct backend service port
    Given the Angular development server is running with proxy.conf.json active
    When the Angular application sends an HTTP request to "<api_prefix>/health"
    Then the dev server forwards the request to "<target_port>"
    And the forwarded request path has the service prefix stripped (e.g., /api/health not /api/workflow/health)

    Examples:
      | api_prefix        | target_port           |
      | /api/workflow     | http://localhost:5001 |
      | /api/kpi          | http://localhost:5002 |
      | /api/admin        | http://localhost:5003 |
      | /api/notifications| http://localhost:5004 |
      | /api/reporting    | http://localhost:5005 |
      | /api/ai-copilot   | http://localhost:5006 |
      | /api/compliance   | http://localhost:5007 |
      | /api/search       | http://localhost:5008 |
      | /api/calendar     | http://localhost:5009 |

  # --- Human-Validation-Only Criteria ---
  # The following acceptance criteria require inspection of configuration file contents
  # and cannot be expressed as automated runtime Gherkin scenarios.
  # They are documented here for traceability and will be handled by validate-acceptance Phase 4.

  # @AC-034 [Human validation]: environment.ts exports a services map with keys:
  #   workflow, kpi, admin, notifications, reporting, aiCopilot, compliance, search, calendar —
  #   each pointing to http://localhost:5001–5009/api.
  # Reason: Verifies TypeScript file content and object shape, not a runtime behaviour.
  #   The runtime correctness of service routing is covered by AC-036.
  # Reviewer: Dev Lead

  # @AC-035 [Human validation]: environment.prod.ts exports the same service map shape with
  #   production-placeholder URLs (https://api.traverse.example.com/{service}).
  # Reason: Production environment values are injected at build time and not reachable in a
  #   local dev Gherkin scenario. File shape verification is a code review task.
  # Reviewer: Dev Lead

  # @AC-037 [Human validation]: angular.json serve options reference proxy.conf.json
  #   (already set in NT-001 stub; verify it is retained after the ng new merge).
  # Reason: Verifies angular.json configuration file content. The functional outcome
  #   (proxying works) is covered by AC-036. The config file itself is a code review check.
  # Reviewer: Dev Lead

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 10:00
