@angular_shell
Feature: Angular workspace compiles cleanly and serves the application shell
  As a developer starting a Phase 1 feature story
  I want an Angular workspace that compiles cleanly and displays the app shell
  So that I can begin adding feature screens without fighting the build setup

  # Traces to: design_angular_shell.md §2 US-001

  # --- Automatable Acceptance Criteria ---

  @AC-002
  Scenario: Production build exits with zero errors
    Given the Angular workspace exists at src/frontend/traverse-workspace
    And the workspace has been bootstrapped with standalone components and strict TypeScript
    When the command "ng build --configuration production" is run
    Then the build process exits with code 0
    And no TypeScript compiler errors are reported
    And no ESLint errors are reported
    And production-ready artefacts are written to the dist folder

  @AC-003
  Scenario: Development server starts and renders the app shell
    Given the Angular workspace compiles without errors
    When the command "ng serve" is run
    Then the development server starts successfully
    And the application is reachable at http://localhost:4200
    And the browser displays a left sidebar navigation panel
    And the browser displays a top navigation bar
    And the browser displays a main content area

  @AC-004
  Scenario: All authored components declare OnPush change detection
    Given the Angular workspace source files are present
    When the source code is inspected for change detection strategy declarations
    Then every Angular component in the workspace declares "changeDetection: ChangeDetectionStrategy.OnPush"
    And no component uses the default "ChangeDetectionStrategy.Default" strategy

  @AC-005
  Scenario: TypeScript strict mode is enabled and no untyped values exist in authored code
    Given the Angular workspace is configured with TypeScript strict mode
    When TypeScript compilation runs across all authored source files
    Then the TypeScript compiler reports zero errors
    And no authored source file contains an explicit "any" type annotation

  # --- Human-Validation-Only Criteria ---
  # The following acceptance criteria require human or tooling inspection of file
  # contents and cannot be expressed as automated runtime Gherkin scenarios.
  # They are documented here for traceability and will be handled by validate-acceptance Phase 4.

  # @AC-001 [Human validation]: ng new is run with correct flags and the NT-001 stub angular.json
  #   and tsconfig.json settings are merged (project name "traverse", OnPush schematic default,
  #   path aliases, proxy.conf.json serve option).
  # Reason: Verifies an implementation-time merge process, not an observable runtime behaviour.
  # Reviewer: Dev Lead

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 10:00
