@angular_shell
Feature: Core providers wire HTTP, routing, animations, and error handling
  As a developer
  I want app.config.ts to register all core providers
  So that every feature component inherits correct HTTP behaviour and error display without additional setup

  # Traces to: design_angular_shell.md §2 US-003 (core providers ACs 011–015)
  #            and US-002 (Material theme ACs 006, 008–010 — human-validation only)

  # --- Automatable Acceptance Criteria ---

  @AC-011
  Scenario: HTTP client is configured with the three core interceptors
    Given the Angular application has bootstrapped
    When an HTTP request is made to any backend API endpoint
    Then the request carries the headers added by authInterceptor
    And the request carries the X-Correlation-Id header added by correlationIdInterceptor
    And HTTP errors from the response are mapped to ApiError by errorInterceptor

  @AC-012
  Scenario: Router is configured and navigation resolves to feature routes
    Given the Angular application has bootstrapped
    When the user navigates to the dashboard route
    Then the Angular router resolves the route successfully
    And the dashboard content area is displayed in the main outlet

  @AC-013
  Scenario: Angular Material animations are active
    Given the Angular application has bootstrapped with animations provided
    When a Material component that uses animations is rendered (e.g., a snackbar or dialog)
    Then the component's enter and exit animations play correctly
    And no "BrowserAnimationsModule not imported" console error appears

  @AC-014
  Scenario: Unhandled Angular errors are caught by the global error handler
    Given the GlobalErrorHandler is registered as the application's ErrorHandler
    When an unhandled error is thrown inside an Angular component
    Then the GlobalErrorHandler intercepts the error before it propagates to the browser console unhandled
    And a dismissible error message is shown to the user via the notification snackbar

  @AC-015
  Scenario Outline: GlobalErrorHandler responds correctly to different error types
    Given the GlobalErrorHandler is registered as the application's ErrorHandler
    When an error of type "<error_type>" occurs in the application
    Then the handler responds with "<expected_behaviour>"

    Examples:
      | error_type                              | expected_behaviour                                                                          |
      | ApiError with HTTP status 401           | The user is redirected to the login page and a snackbar message is shown                   |
      | ApiError with HTTP status other than 401| A snackbar notification displays the error detail message from the ApiError problem object |
      | Generic JavaScript Error                | The error is logged to the browser console and a generic error snackbar is shown           |

  # --- Human-Validation-Only Criteria ---
  # The following acceptance criteria require inspection of source file contents
  # and cannot be expressed as automated runtime Gherkin scenarios.
  # They are documented here for traceability and will be handled by validate-acceptance Phase 4.

  # @AC-006 [Human validation]: src/styles/theme.scss uses mat.define-theme() with a custom
  #   Traverse palette seeded from #1e4d8c, using mat.$azure-palette as the built-in seed.
  # Reason: Verifies file content and Sass API usage, not an observable runtime behaviour.
  # Reviewer: Dev Lead

  # @AC-008 [Human validation]: src/styles.scss declares token aliases, typography reset
  #   (Segoe UI/Arial, 13px base body, 14px for labels), and layout primitives (shell grid,
  #   sidebar width variable, content area padding).
  # Reason: Verifies SCSS file structure and variable declarations, not observable UI behaviour
  #   (the rendered output is covered by AC-003 and the component scenarios).
  # Reviewer: Dev Lead

  # @AC-009 [Human validation]: No hardcoded hex or RGB colour values appear in any component
  #   stylesheet — only --mat-sys-* or --traverse-status-* tokens are used.
  # Reason: Requires static analysis of all .scss files; cannot be reliably asserted from
  #   browser-observable behaviour without inspecting computed styles for every element.
  # Reviewer: Dev Lead (code review)

  # @AC-010 [Human validation]: *.scss and *.css files have LF line endings enforced in
  #   .gitattributes (SF-1 carryover from NT-001 code review).
  # Reason: Line-ending enforcement is a git-level attribute, not an observable application
  #   behaviour. Verified by inspecting .gitattributes and running git check-attr.
  # Reviewer: Dev Lead

# Generated by skill: generate-gherkin v2.2.0 | 2026-04-30 10:00
